import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // ── Admin User ──────────────────────────────────────────────────────
  const passwordHash = await bcrypt.hash("Lib12345", 12);
  const user = await prisma.user.upsert({
    where: { email: "sanhanat_p@libcon.co.jp" },
    update: {},
    create: {
      name: "Sanhanat P",
      email: "sanhanat_p@libcon.co.jp",
      passwordHash,
    },
  });
  console.log(`  Admin user: ${user.email} (id: ${user.id})`);

  // ── Demo Accounts ───────────────────────────────────────────────────
  const accounts = await Promise.all([
    prisma.account.upsert({
      where: { id: "ACC-001" },
      update: {},
      create: {
        id: "ACC-001",
        name: "Toyota Motor Thailand",
        type: "Customer",
        industry: "Automotive",
        phone: "+66-2-386-1000",
        website: "https://www.toyota.co.th",
        billingStreet: "186/1 Moo 1, Old Railway Rd",
        billingCity: "Samrong Tai",
        billingState: "Samut Prakan",
        billingPostalCode: "10280",
        billingCountry: "Thailand",
        annualRevenue: 150000000,
        numberOfEmployees: 12000,
        description: "Leading automotive manufacturer in Thailand",
        rating: "Hot",
        accountStatus: "Active",
        national: "Japanese",
        numberOfProjects: 5,
        totalRevenue: 2500000,
        createdDate: new Date("2024-01-15"),
        lastModifiedDate: new Date("2025-12-01"),
      },
    }),
    prisma.account.upsert({
      where: { id: "ACC-002" },
      update: {},
      create: {
        id: "ACC-002",
        name: "SCG Chemicals",
        type: "Customer",
        industry: "Chemicals",
        phone: "+66-2-586-4444",
        website: "https://www.scgchemicals.com",
        billingStreet: "1 Siam Cement Rd",
        billingCity: "Bang Sue",
        billingState: "Bangkok",
        billingPostalCode: "10800",
        billingCountry: "Thailand",
        annualRevenue: 80000000,
        numberOfEmployees: 5000,
        description: "Major petrochemical and chemical company",
        rating: "Warm",
        accountStatus: "Active",
        national: "Thai",
        numberOfProjects: 3,
        totalRevenue: 1200000,
        createdDate: new Date("2024-03-20"),
        lastModifiedDate: new Date("2025-11-15"),
      },
    }),
    prisma.account.upsert({
      where: { id: "ACC-003" },
      update: {},
      create: {
        id: "ACC-003",
        name: "Denso Thailand",
        type: "Prospect",
        industry: "Automotive Parts",
        phone: "+66-2-769-5000",
        website: "https://www.denso.com/th",
        billingStreet: "99 Moo 2, Bangna-Trad Rd",
        billingCity: "Bang Phli",
        billingState: "Samut Prakan",
        billingPostalCode: "10540",
        billingCountry: "Thailand",
        annualRevenue: 45000000,
        numberOfEmployees: 8000,
        description: "Automotive components manufacturer",
        rating: "Warm",
        accountStatus: "Active",
        national: "Japanese",
        numberOfProjects: 1,
        totalRevenue: 350000,
        createdDate: new Date("2024-06-10"),
        lastModifiedDate: new Date("2025-10-20"),
      },
    }),
    prisma.account.upsert({
      where: { id: "ACC-004" },
      update: {},
      create: {
        id: "ACC-004",
        name: "Kasikornbank PCL",
        type: "Customer",
        industry: "Banking",
        phone: "+66-2-888-8888",
        website: "https://www.kasikornbank.com",
        billingStreet: "1 Soi Kasikorn, Rat Burana Rd",
        billingCity: "Rat Burana",
        billingState: "Bangkok",
        billingPostalCode: "10140",
        billingCountry: "Thailand",
        annualRevenue: 200000000,
        numberOfEmployees: 20000,
        description: "One of Thailand's largest commercial banks",
        rating: "Hot",
        accountStatus: "Active",
        national: "Thai",
        numberOfProjects: 4,
        totalRevenue: 1800000,
        createdDate: new Date("2024-02-01"),
        lastModifiedDate: new Date("2025-12-10"),
      },
    }),
    prisma.account.upsert({
      where: { id: "ACC-005" },
      update: {},
      create: {
        id: "ACC-005",
        name: "Mitsubishi Electric Thai Auto-Parts",
        type: "Prospect",
        industry: "Electronics",
        phone: "+66-2-312-5500",
        website: "https://www.mitsubishielectric.co.th",
        billingStreet: "12 Moo 4, Bangna-Trad Rd KM.23",
        billingCity: "Bang Bo",
        billingState: "Samut Prakan",
        billingPostalCode: "10560",
        billingCountry: "Thailand",
        annualRevenue: 30000000,
        numberOfEmployees: 3000,
        description: "Electronics and electrical equipment manufacturer",
        rating: "Cold",
        accountStatus: "Inactive",
        national: "Japanese",
        numberOfProjects: 0,
        totalRevenue: 0,
        createdDate: new Date("2025-01-05"),
        lastModifiedDate: new Date("2025-09-30"),
      },
    }),
  ]);
  console.log(`  Created ${accounts.length} demo accounts`);

  // ── Demo Contacts ───────────────────────────────────────────────────
  const contacts = await Promise.all([
    prisma.contact.upsert({
      where: { id: "CON-001" },
      update: {},
      create: {
        id: "CON-001",
        accountId: "ACC-001",
        salutation: "Mr.",
        firstName: "Takeshi",
        lastName: "Yamamoto",
        email: "takeshi.y@toyota.co.th",
        phone: "+66-2-386-1001",
        mobilePhone: "+66-81-234-5678",
        title: "VP of Supply Chain",
        department: "Supply Chain Management",
        mailingCity: "Samrong Tai",
        mailingState: "Samut Prakan",
        mailingCountry: "Thailand",
        leadSource: "Referral",
        contactStatus: "Active",
        executiveOrNot: true,
        rating: "Hot",
        titleFormat: "VP",
        worthFollowing: true,
        personCountry: "Japanese",
        createdDate: new Date("2024-01-20"),
        lastModifiedDate: new Date("2025-11-05"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-002" },
      update: {},
      create: {
        id: "CON-002",
        accountId: "ACC-001",
        salutation: "Ms.",
        firstName: "Siriporn",
        lastName: "Thongkham",
        email: "siriporn.t@toyota.co.th",
        phone: "+66-2-386-1050",
        mobilePhone: "+66-89-876-5432",
        title: "Procurement Manager",
        department: "Procurement",
        mailingCity: "Samrong Tai",
        mailingState: "Samut Prakan",
        mailingCountry: "Thailand",
        leadSource: "Trade Show",
        contactStatus: "Active",
        executiveOrNot: false,
        rating: "Warm",
        titleFormat: "Manager",
        worthFollowing: true,
        personCountry: "Thai",
        createdDate: new Date("2024-02-10"),
        lastModifiedDate: new Date("2025-10-20"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-003" },
      update: {},
      create: {
        id: "CON-003",
        accountId: "ACC-002",
        salutation: "Mr.",
        firstName: "Somchai",
        lastName: "Prachakul",
        email: "somchai.p@scgchemicals.com",
        phone: "+66-2-586-4500",
        mobilePhone: "+66-82-111-2233",
        title: "Director of Operations",
        department: "Operations",
        mailingCity: "Bang Sue",
        mailingState: "Bangkok",
        mailingCountry: "Thailand",
        leadSource: "Website",
        contactStatus: "Active",
        executiveOrNot: true,
        rating: "Hot",
        titleFormat: "Director",
        worthFollowing: true,
        personCountry: "Thai",
        createdDate: new Date("2024-03-25"),
        lastModifiedDate: new Date("2025-11-30"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-004" },
      update: {},
      create: {
        id: "CON-004",
        accountId: "ACC-003",
        salutation: "Mr.",
        firstName: "Kenji",
        lastName: "Nakamura",
        email: "kenji.n@denso.co.th",
        phone: "+66-2-769-5010",
        mobilePhone: "+66-83-444-5566",
        title: "General Manager",
        department: "Engineering",
        mailingCity: "Bang Phli",
        mailingState: "Samut Prakan",
        mailingCountry: "Thailand",
        leadSource: "Referral",
        contactStatus: "Active",
        executiveOrNot: true,
        rating: "Warm",
        titleFormat: "GM",
        worthFollowing: true,
        personCountry: "Japanese",
        createdDate: new Date("2024-06-15"),
        lastModifiedDate: new Date("2025-10-01"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-005" },
      update: {},
      create: {
        id: "CON-005",
        accountId: "ACC-004",
        salutation: "Ms.",
        firstName: "Pimchanok",
        lastName: "Srisawat",
        email: "pimchanok.s@kasikornbank.com",
        phone: "+66-2-888-8001",
        mobilePhone: "+66-86-777-8899",
        title: "SVP Digital Transformation",
        department: "Digital Banking",
        mailingCity: "Rat Burana",
        mailingState: "Bangkok",
        mailingCountry: "Thailand",
        leadSource: "Conference",
        contactStatus: "Active",
        executiveOrNot: true,
        rating: "Hot",
        titleFormat: "SVP",
        worthFollowing: true,
        personCountry: "Thai",
        createdDate: new Date("2024-02-15"),
        lastModifiedDate: new Date("2025-12-05"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-006" },
      update: {},
      create: {
        id: "CON-006",
        accountId: "ACC-004",
        salutation: "Mr.",
        firstName: "Wichai",
        lastName: "Boonma",
        email: "wichai.b@kasikornbank.com",
        phone: "+66-2-888-8100",
        title: "IT Infrastructure Manager",
        department: "Information Technology",
        mailingCity: "Rat Burana",
        mailingState: "Bangkok",
        mailingCountry: "Thailand",
        leadSource: "Website",
        contactStatus: "Active",
        executiveOrNot: false,
        rating: "Warm",
        titleFormat: "Manager",
        worthFollowing: false,
        personCountry: "Thai",
        createdDate: new Date("2024-04-01"),
        lastModifiedDate: new Date("2025-11-20"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-007" },
      update: {},
      create: {
        id: "CON-007",
        accountId: "ACC-002",
        salutation: "Ms.",
        firstName: "Narumon",
        lastName: "Chantra",
        email: "narumon.c@scgchemicals.com",
        phone: "+66-2-586-4600",
        mobilePhone: "+66-84-222-3344",
        title: "Safety & Environment Manager",
        department: "EHS",
        mailingCity: "Bang Sue",
        mailingState: "Bangkok",
        mailingCountry: "Thailand",
        leadSource: "Referral",
        contactStatus: "Active",
        executiveOrNot: false,
        rating: "Warm",
        titleFormat: "Manager",
        worthFollowing: true,
        personCountry: "Thai",
        createdDate: new Date("2024-05-10"),
        lastModifiedDate: new Date("2025-09-15"),
      },
    }),
    prisma.contact.upsert({
      where: { id: "CON-008" },
      update: {},
      create: {
        id: "CON-008",
        accountId: "ACC-005",
        salutation: "Mr.",
        firstName: "Hiroshi",
        lastName: "Tanaka",
        email: "hiroshi.t@mitsubishielectric.co.th",
        phone: "+66-2-312-5501",
        title: "President",
        department: "Executive",
        mailingCity: "Bang Bo",
        mailingState: "Samut Prakan",
        mailingCountry: "Thailand",
        leadSource: "Cold Call",
        contactStatus: "Inactive",
        executiveOrNot: true,
        rating: "Cold",
        titleFormat: "President",
        worthFollowing: false,
        personCountry: "Japanese",
        createdDate: new Date("2025-01-10"),
        lastModifiedDate: new Date("2025-09-30"),
      },
    }),
  ]);
  console.log(`  Created ${contacts.length} demo contacts`);

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
